name: verify

on:
  pull_request:
  push:

jobs:
  all:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]  # Use major versions for clarity

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8  # Keep the pnpm version here

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color

      - name: E2E Smoke Test
        if: matrix.os == 'ubuntu-latest'
        run: ./test/smoke.sh

      - name: Lint
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20'
        run: pnpm run lint
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color

      - name: Test
        run: pnpm run test
        env:
          FORCE_COLOR: 3
          TERM: xterm-256color
